# Generated by Django 4.1.4 on 2023-01-27 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tournament_website", "0002_fightermodel_user_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fightermodel",
            name="user_profile",
            field=models.OneToOneField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
