# Generated by Django 4.1.4 on 2023-01-27 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tournament_website", "0003_alter_fightermodel_user_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="FighterDjangoModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("weight", models.FloatField()),
                (
                    "belt",
                    models.DecimalField(
                        choices=[
                            (0, "White"),
                            (1, "Blue"),
                            (2, "Purple"),
                            (3, "Brown"),
                            (4, "Black"),
                        ],
                        decimal_places=1,
                        max_digits=1,
                    ),
                ),
                ("age", models.DecimalField(decimal_places=1, max_digits=3)),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.UUID("f40a5912-bde9-4c89-9807-ec5a479b57e1")
                    ),
                ),
                (
                    "user_profile",
                    models.OneToOneField(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="FighterModel",
        ),
    ]
