# Generated by Django 4.1.4 on 2023-02-10 17:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("tournament_website", "0008_alter_fighterdjangomodel_uid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fighterdjangomodel",
            name="uid",
            field=models.UUIDField(
                default=uuid.UUID("06226199-f173-44d2-b4eb-8bfd96e7f1ba")
            ),
        ),
        migrations.CreateModel(
            name="TournamentDjangoModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("participant_limit", models.IntegerField()),
                ("description", models.TextField(max_length=500)),
                (
                    "participants",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournament",
                        to="tournament_website.fighterdjangomodel",
                    ),
                ),
            ],
        ),
    ]
