# Generated by Django 4.1.4 on 2023-02-14 22:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        (
            "tournament_website",
            "0010_remove_tournamentdjangomodel_participants_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="fighterdjangomodel",
            name="uid",
            field=models.UUIDField(
                default=uuid.UUID("b0365fc1-1264-4a47-ae0c-9d1b51454622")
            ),
        ),
    ]
