# Generated by Django 4.1.4 on 2023-02-14 22:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("tournament_website", "0011_alter_fighterdjangomodel_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fighterdjangomodel",
            name="tournament",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants",
                to="tournament_website.tournamentdjangomodel",
            ),
        ),
        migrations.AlterField(
            model_name="fighterdjangomodel",
            name="uid",
            field=models.UUIDField(
                default=uuid.UUID("7bdf6269-ea54-49d8-bff3-cca81ae0b5bf")
            ),
        ),
    ]
